apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qpi5stfsq-python
  janus-idp.io/tekton: qpi5stfsq-python
  backstage.io/kubernetes-id: qpi5stfsq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qpi5stfsq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
